logging:
  level: 
    org:
      springframework: WARN
      hibernate: WARN
    com:
      menulabs:
        taxisplus: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost/taxisplus?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: 1337h4x  
    driverClassName: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLInnoDBDialect
      ddl-auto: none
    generate-ddl: false
    show-sql: true
  freemarker:
    expose-request-attributes: true
    expose-spring-macro-helpers: true

# Keep the connection alive if idle for a long time (needed in production)
# Show or not log for each sql query
# Hibernate ddl auto (create, create-drop, update)